apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec: 
  selector: 
    app: frontend-app 
  ports: 
  - name: angular 
    targetPort: 30080
    port: 30080
    nodePort: 30080  # Explicitly specify the NodePort
  type: NodePort 
